// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    [Migration("20251224154238_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Title = "Clean Code",
                            YearPublished = 2008
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            Title = "The Pragmatic Programmer",
                            YearPublished = 1999
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma",
                            Title = "Design Patterns",
                            YearPublished = 1994
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Fowler",
                            Title = "Refactoring",
                            YearPublished = 1999
                        },
                        new
                        {
                            Id = 5,
                            Author = "Thomas H. Cormen",
                            Title = "Introduction to Algorithms",
                            YearPublished = 2009
                        },
                        new
                        {
                            Id = 6,
                            Author = "Eric Freeman",
                            Title = "Head First Design Patterns",
                            YearPublished = 2004
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kyle Simpson",
                            Title = "You Don’t Know JS",
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 8,
                            Author = "Joshua Bloch",
                            Title = "Effective Java",
                            YearPublished = 2001
                        },
                        new
                        {
                            Id = 9,
                            Author = "Jon Skeet",
                            Title = "C# in Depth",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 10,
                            Author = "Alex Xu",
                            Title = "System Design Interview",
                            YearPublished = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
